### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by uroboro** [theos/logos#2]
- [ ] Add several improvements from [Logos Improvements](https://github.com/theos/theos/issues/60).
- [ ] Rewrite logos.pl as proper parser instead of regex.
- Would fix [Logos errors out on calling %orig with an inline block with multiple lines](https://github.com/theos/theos/issues/83).
- Would help fix [%subclass should provide an @interface](https://github.com/theos/theos/issues/100).
- Would help fix [Make Logos stderr output similar to clang](https://github.com/theos/theos/issues/208).
- Would help fix [Dynamically looking-up classes beside bracketed math causes compiling error](https://github.com/theos/theos/issues/257).
- [ ] Fix [No dependency ordering in Logos](https://github.com/theos/theos/issues/86).
- [ ] Fix [%subclass with protocols crashes in the constructor](https://github.com/theos/theos/issues/114).
- [x] Fix [Allow hooking of swift classes](https://github.com/theos/theos/issues/153).
- [ ] Fix `%log` [Error while debugging NSBlock](https://github.com/theos/theos/issues/237).
- [x] Fix [CGFloat %property wrongly assumes float, crashes on 32-bit](https://github.com/theos/theos/issues/243).
- [ ] Add function support to `%log`. (See [buildLogCall](https://github.com/theos/logos/blob/master/bin/lib/Logos/Generator/Base/Method.pm#L68))

**Comment by uroboro** [comment]
Consider [BlockTypeDescription](https://github.com/conradev/BlockTypeDescription) for logging blocks on runtime.
